// Code generated by MockGen. DO NOT EDIT.
// Source: escort-book-escort-profile/singleton (interfaces: IKafka)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	kafka "github.com/confluentinc/confluent-kafka-go/kafka"
	gomock "github.com/golang/mock/gomock"
)

// MockIKafka is a mock of IKafka interface.
type MockIKafka struct {
	ctrl     *gomock.Controller
	recorder *MockIKafkaMockRecorder
}

// MockIKafkaMockRecorder is the mock recorder for MockIKafka.
type MockIKafkaMockRecorder struct {
	mock *MockIKafka
}

// NewMockIKafka creates a new mock instance.
func NewMockIKafka(ctrl *gomock.Controller) *MockIKafka {
	mock := &MockIKafka{ctrl: ctrl}
	mock.recorder = &MockIKafkaMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIKafka) EXPECT() *MockIKafkaMockRecorder {
	return m.recorder
}

// Produce mocks base method.
func (m *MockIKafka) Produce(arg0 *kafka.Message, arg1 chan kafka.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Produce", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Produce indicates an expected call of Produce.
func (mr *MockIKafkaMockRecorder) Produce(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Produce", reflect.TypeOf((*MockIKafka)(nil).Produce), arg0, arg1)
}
