// Code generated by MockGen. DO NOT EDIT.
// Source: escort-book-escort-profile/singleton (interfaces: IS3)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	s3 "github.com/aws/aws-sdk-go/service/s3"
	gomock "github.com/golang/mock/gomock"
)

// MockIS3 is a mock of IS3 interface.
type MockIS3 struct {
	ctrl     *gomock.Controller
	recorder *MockIS3MockRecorder
}

// MockIS3MockRecorder is the mock recorder for MockIS3.
type MockIS3MockRecorder struct {
	mock *MockIS3
}

// NewMockIS3 creates a new mock instance.
func NewMockIS3(ctrl *gomock.Controller) *MockIS3 {
	mock := &MockIS3{ctrl: ctrl}
	mock.recorder = &MockIS3MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIS3) EXPECT() *MockIS3MockRecorder {
	return m.recorder
}

// PutObject mocks base method.
func (m *MockIS3) PutObject(arg0 *s3.PutObjectInput) (*s3.PutObjectOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutObject", arg0)
	ret0, _ := ret[0].(*s3.PutObjectOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutObject indicates an expected call of PutObject.
func (mr *MockIS3MockRecorder) PutObject(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutObject", reflect.TypeOf((*MockIS3)(nil).PutObject), arg0)
}
