// Code generated by MockGen. DO NOT EDIT.
// Source: escort-book-escort-profile/services (interfaces: IS3Service)

// Package mocks is a generated GoMock package.
package mocks

import (
	multipart "mime/multipart"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIS3Service is a mock of IS3Service interface.
type MockIS3Service struct {
	ctrl     *gomock.Controller
	recorder *MockIS3ServiceMockRecorder
}

// MockIS3ServiceMockRecorder is the mock recorder for MockIS3Service.
type MockIS3ServiceMockRecorder struct {
	mock *MockIS3Service
}

// NewMockIS3Service creates a new mock instance.
func NewMockIS3Service(ctrl *gomock.Controller) *MockIS3Service {
	mock := &MockIS3Service{ctrl: ctrl}
	mock.recorder = &MockIS3ServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIS3Service) EXPECT() *MockIS3ServiceMockRecorder {
	return m.recorder
}

// Upload mocks base method.
func (m *MockIS3Service) Upload(arg0, arg1, arg2 string, arg3 multipart.File) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockIS3ServiceMockRecorder) Upload(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockIS3Service)(nil).Upload), arg0, arg1, arg2, arg3)
}
