// Code generated by MockGen. DO NOT EDIT.
// Source: escort-book-escort-profile/repositories (interfaces: IAttentionSiteCategoryRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "escort-book-escort-profile/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIAttentionSiteCategoryRepository is a mock of IAttentionSiteCategoryRepository interface.
type MockIAttentionSiteCategoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIAttentionSiteCategoryRepositoryMockRecorder
}

// MockIAttentionSiteCategoryRepositoryMockRecorder is the mock recorder for MockIAttentionSiteCategoryRepository.
type MockIAttentionSiteCategoryRepositoryMockRecorder struct {
	mock *MockIAttentionSiteCategoryRepository
}

// NewMockIAttentionSiteCategoryRepository creates a new mock instance.
func NewMockIAttentionSiteCategoryRepository(ctrl *gomock.Controller) *MockIAttentionSiteCategoryRepository {
	mock := &MockIAttentionSiteCategoryRepository{ctrl: ctrl}
	mock.recorder = &MockIAttentionSiteCategoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAttentionSiteCategoryRepository) EXPECT() *MockIAttentionSiteCategoryRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockIAttentionSiteCategoryRepository) Count(arg0 context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockIAttentionSiteCategoryRepositoryMockRecorder) Count(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockIAttentionSiteCategoryRepository)(nil).Count), arg0)
}

// GetAll mocks base method.
func (m *MockIAttentionSiteCategoryRepository) GetAll(arg0 context.Context, arg1, arg2 int) ([]models.AttentionSiteCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", arg0, arg1, arg2)
	ret0, _ := ret[0].([]models.AttentionSiteCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockIAttentionSiteCategoryRepositoryMockRecorder) GetAll(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockIAttentionSiteCategoryRepository)(nil).GetAll), arg0, arg1, arg2)
}

// GetById mocks base method.
func (m *MockIAttentionSiteCategoryRepository) GetById(arg0 context.Context, arg1 string) (models.AttentionSiteCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", arg0, arg1)
	ret0, _ := ret[0].(models.AttentionSiteCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockIAttentionSiteCategoryRepositoryMockRecorder) GetById(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockIAttentionSiteCategoryRepository)(nil).GetById), arg0, arg1)
}
