// Code generated by MockGen. DO NOT EDIT.
// Source: escort-book-escort-profile/repositories (interfaces: IDayRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "escort-book-escort-profile/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIDayRepository is a mock of IDayRepository interface.
type MockIDayRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIDayRepositoryMockRecorder
}

// MockIDayRepositoryMockRecorder is the mock recorder for MockIDayRepository.
type MockIDayRepositoryMockRecorder struct {
	mock *MockIDayRepository
}

// NewMockIDayRepository creates a new mock instance.
func NewMockIDayRepository(ctrl *gomock.Controller) *MockIDayRepository {
	mock := &MockIDayRepository{ctrl: ctrl}
	mock.recorder = &MockIDayRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDayRepository) EXPECT() *MockIDayRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockIDayRepository) Count(arg0 context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockIDayRepositoryMockRecorder) Count(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockIDayRepository)(nil).Count), arg0)
}

// GetAll mocks base method.
func (m *MockIDayRepository) GetAll(arg0 context.Context, arg1, arg2 int) ([]models.Day, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", arg0, arg1, arg2)
	ret0, _ := ret[0].([]models.Day)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockIDayRepositoryMockRecorder) GetAll(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockIDayRepository)(nil).GetAll), arg0, arg1, arg2)
}

// GetById mocks base method.
func (m *MockIDayRepository) GetById(arg0 context.Context, arg1 string) (models.Day, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", arg0, arg1)
	ret0, _ := ret[0].(models.Day)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockIDayRepositoryMockRecorder) GetById(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockIDayRepository)(nil).GetById), arg0, arg1)
}

// GetOneByName mocks base method.
func (m *MockIDayRepository) GetOneByName(arg0 context.Context, arg1 string) (models.Day, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOneByName", arg0, arg1)
	ret0, _ := ret[0].(models.Day)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOneByName indicates an expected call of GetOneByName.
func (mr *MockIDayRepositoryMockRecorder) GetOneByName(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOneByName", reflect.TypeOf((*MockIDayRepository)(nil).GetOneByName), arg0, arg1)
}
