// Code generated by MockGen. DO NOT EDIT.
// Source: escort-book-escort-profile/repositories (interfaces: IIdentificationPartRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "escort-book-escort-profile/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIIdentificationPartRepository is a mock of IIdentificationPartRepository interface.
type MockIIdentificationPartRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIIdentificationPartRepositoryMockRecorder
}

// MockIIdentificationPartRepositoryMockRecorder is the mock recorder for MockIIdentificationPartRepository.
type MockIIdentificationPartRepositoryMockRecorder struct {
	mock *MockIIdentificationPartRepository
}

// NewMockIIdentificationPartRepository creates a new mock instance.
func NewMockIIdentificationPartRepository(ctrl *gomock.Controller) *MockIIdentificationPartRepository {
	mock := &MockIIdentificationPartRepository{ctrl: ctrl}
	mock.recorder = &MockIIdentificationPartRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIIdentificationPartRepository) EXPECT() *MockIIdentificationPartRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockIIdentificationPartRepository) Count(arg0 context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockIIdentificationPartRepositoryMockRecorder) Count(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockIIdentificationPartRepository)(nil).Count), arg0)
}

// GetAll mocks base method.
func (m *MockIIdentificationPartRepository) GetAll(arg0 context.Context, arg1, arg2 int) ([]models.IdentificationPart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", arg0, arg1, arg2)
	ret0, _ := ret[0].([]models.IdentificationPart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockIIdentificationPartRepositoryMockRecorder) GetAll(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockIIdentificationPartRepository)(nil).GetAll), arg0, arg1, arg2)
}

// GetById mocks base method.
func (m *MockIIdentificationPartRepository) GetById(arg0 context.Context, arg1 string) (models.IdentificationPart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", arg0, arg1)
	ret0, _ := ret[0].(models.IdentificationPart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockIIdentificationPartRepositoryMockRecorder) GetById(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockIIdentificationPartRepository)(nil).GetById), arg0, arg1)
}
