// Code generated by MockGen. DO NOT EDIT.
// Source: escort-book-escort-profile/repositories (interfaces: INationalityRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "escort-book-escort-profile/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockINationalityRepository is a mock of INationalityRepository interface.
type MockINationalityRepository struct {
	ctrl     *gomock.Controller
	recorder *MockINationalityRepositoryMockRecorder
}

// MockINationalityRepositoryMockRecorder is the mock recorder for MockINationalityRepository.
type MockINationalityRepositoryMockRecorder struct {
	mock *MockINationalityRepository
}

// NewMockINationalityRepository creates a new mock instance.
func NewMockINationalityRepository(ctrl *gomock.Controller) *MockINationalityRepository {
	mock := &MockINationalityRepository{ctrl: ctrl}
	mock.recorder = &MockINationalityRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockINationalityRepository) EXPECT() *MockINationalityRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockINationalityRepository) Count(arg0 context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockINationalityRepositoryMockRecorder) Count(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockINationalityRepository)(nil).Count), arg0)
}

// GetAll mocks base method.
func (m *MockINationalityRepository) GetAll(arg0 context.Context, arg1, arg2 int) ([]models.Nationality, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", arg0, arg1, arg2)
	ret0, _ := ret[0].([]models.Nationality)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockINationalityRepositoryMockRecorder) GetAll(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockINationalityRepository)(nil).GetAll), arg0, arg1, arg2)
}

// GetById mocks base method.
func (m *MockINationalityRepository) GetById(arg0 context.Context, arg1 string) (models.Nationality, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", arg0, arg1)
	ret0, _ := ret[0].(models.Nationality)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockINationalityRepositoryMockRecorder) GetById(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockINationalityRepository)(nil).GetById), arg0, arg1)
}
