// Code generated by MockGen. DO NOT EDIT.
// Source: escort-book-escort-profile/repositories (interfaces: IPriceRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "escort-book-escort-profile/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIPriceRepository is a mock of IPriceRepository interface.
type MockIPriceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIPriceRepositoryMockRecorder
}

// MockIPriceRepositoryMockRecorder is the mock recorder for MockIPriceRepository.
type MockIPriceRepositoryMockRecorder struct {
	mock *MockIPriceRepository
}

// NewMockIPriceRepository creates a new mock instance.
func NewMockIPriceRepository(ctrl *gomock.Controller) *MockIPriceRepository {
	mock := &MockIPriceRepository{ctrl: ctrl}
	mock.recorder = &MockIPriceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPriceRepository) EXPECT() *MockIPriceRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockIPriceRepository) Count(arg0 context.Context, arg1 string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockIPriceRepositoryMockRecorder) Count(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockIPriceRepository)(nil).Count), arg0, arg1)
}

// Create mocks base method.
func (m *MockIPriceRepository) Create(arg0 context.Context, arg1 *models.Price) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIPriceRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIPriceRepository)(nil).Create), arg0, arg1)
}

// DeleteOne mocks base method.
func (m *MockIPriceRepository) DeleteOne(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOne", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOne indicates an expected call of DeleteOne.
func (mr *MockIPriceRepositoryMockRecorder) DeleteOne(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOne", reflect.TypeOf((*MockIPriceRepository)(nil).DeleteOne), arg0, arg1)
}

// GetAll mocks base method.
func (m *MockIPriceRepository) GetAll(arg0 context.Context, arg1 string, arg2, arg3 int) ([]models.Price, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]models.Price)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockIPriceRepositoryMockRecorder) GetAll(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockIPriceRepository)(nil).GetAll), arg0, arg1, arg2, arg3)
}

// GetOne mocks base method.
func (m *MockIPriceRepository) GetOne(arg0 context.Context, arg1 string) (models.Price, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOne", arg0, arg1)
	ret0, _ := ret[0].(models.Price)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOne indicates an expected call of GetOne.
func (mr *MockIPriceRepositoryMockRecorder) GetOne(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOne", reflect.TypeOf((*MockIPriceRepository)(nil).GetOne), arg0, arg1)
}

// UpdateOne mocks base method.
func (m *MockIPriceRepository) UpdateOne(arg0 context.Context, arg1 string, arg2 *models.Price) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOne", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOne indicates an expected call of UpdateOne.
func (mr *MockIPriceRepositoryMockRecorder) UpdateOne(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOne", reflect.TypeOf((*MockIPriceRepository)(nil).UpdateOne), arg0, arg1, arg2)
}
