// Code generated by MockGen. DO NOT EDIT.
// Source: escort-book-escort-profile/repositories (interfaces: IScheduleRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "escort-book-escort-profile/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIScheduleRepository is a mock of IScheduleRepository interface.
type MockIScheduleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIScheduleRepositoryMockRecorder
}

// MockIScheduleRepositoryMockRecorder is the mock recorder for MockIScheduleRepository.
type MockIScheduleRepositoryMockRecorder struct {
	mock *MockIScheduleRepository
}

// NewMockIScheduleRepository creates a new mock instance.
func NewMockIScheduleRepository(ctrl *gomock.Controller) *MockIScheduleRepository {
	mock := &MockIScheduleRepository{ctrl: ctrl}
	mock.recorder = &MockIScheduleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIScheduleRepository) EXPECT() *MockIScheduleRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockIScheduleRepository) Count(arg0 context.Context, arg1 string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockIScheduleRepositoryMockRecorder) Count(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockIScheduleRepository)(nil).Count), arg0, arg1)
}

// Create mocks base method.
func (m *MockIScheduleRepository) Create(arg0 context.Context, arg1 *models.Schedule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIScheduleRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIScheduleRepository)(nil).Create), arg0, arg1)
}

// DeleteOne mocks base method.
func (m *MockIScheduleRepository) DeleteOne(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOne", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOne indicates an expected call of DeleteOne.
func (mr *MockIScheduleRepositoryMockRecorder) DeleteOne(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOne", reflect.TypeOf((*MockIScheduleRepository)(nil).DeleteOne), arg0, arg1)
}

// GetAll mocks base method.
func (m *MockIScheduleRepository) GetAll(arg0 context.Context, arg1 string, arg2, arg3 int) ([]models.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]models.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockIScheduleRepositoryMockRecorder) GetAll(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockIScheduleRepository)(nil).GetAll), arg0, arg1, arg2, arg3)
}

// GetOne mocks base method.
func (m *MockIScheduleRepository) GetOne(arg0 context.Context, arg1 string) (models.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOne", arg0, arg1)
	ret0, _ := ret[0].(models.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOne indicates an expected call of GetOne.
func (mr *MockIScheduleRepositoryMockRecorder) GetOne(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOne", reflect.TypeOf((*MockIScheduleRepository)(nil).GetOne), arg0, arg1)
}
