// Code generated by MockGen. DO NOT EDIT.
// Source: escort-book-escort-profile/repositories (interfaces: IServiceCategoryRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "escort-book-escort-profile/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIServiceCategoryRepository is a mock of IServiceCategoryRepository interface.
type MockIServiceCategoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIServiceCategoryRepositoryMockRecorder
}

// MockIServiceCategoryRepositoryMockRecorder is the mock recorder for MockIServiceCategoryRepository.
type MockIServiceCategoryRepositoryMockRecorder struct {
	mock *MockIServiceCategoryRepository
}

// NewMockIServiceCategoryRepository creates a new mock instance.
func NewMockIServiceCategoryRepository(ctrl *gomock.Controller) *MockIServiceCategoryRepository {
	mock := &MockIServiceCategoryRepository{ctrl: ctrl}
	mock.recorder = &MockIServiceCategoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIServiceCategoryRepository) EXPECT() *MockIServiceCategoryRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockIServiceCategoryRepository) Count(arg0 context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockIServiceCategoryRepositoryMockRecorder) Count(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockIServiceCategoryRepository)(nil).Count), arg0)
}

// GetAll mocks base method.
func (m *MockIServiceCategoryRepository) GetAll(arg0 context.Context, arg1, arg2 int) ([]models.ServiceCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", arg0, arg1, arg2)
	ret0, _ := ret[0].([]models.ServiceCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockIServiceCategoryRepositoryMockRecorder) GetAll(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockIServiceCategoryRepository)(nil).GetAll), arg0, arg1, arg2)
}

// GetById mocks base method.
func (m *MockIServiceCategoryRepository) GetById(arg0 context.Context, arg1 string) (models.ServiceCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", arg0, arg1)
	ret0, _ := ret[0].(models.ServiceCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockIServiceCategoryRepositoryMockRecorder) GetById(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockIServiceCategoryRepository)(nil).GetById), arg0, arg1)
}
