// Code generated by MockGen. DO NOT EDIT.
// Source: escort-book-escort-profile/repositories (interfaces: IServiceRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "escort-book-escort-profile/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIServiceRepository is a mock of IServiceRepository interface.
type MockIServiceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIServiceRepositoryMockRecorder
}

// MockIServiceRepositoryMockRecorder is the mock recorder for MockIServiceRepository.
type MockIServiceRepositoryMockRecorder struct {
	mock *MockIServiceRepository
}

// NewMockIServiceRepository creates a new mock instance.
func NewMockIServiceRepository(ctrl *gomock.Controller) *MockIServiceRepository {
	mock := &MockIServiceRepository{ctrl: ctrl}
	mock.recorder = &MockIServiceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIServiceRepository) EXPECT() *MockIServiceRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockIServiceRepository) Count(arg0 context.Context, arg1 string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockIServiceRepositoryMockRecorder) Count(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockIServiceRepository)(nil).Count), arg0, arg1)
}

// Create mocks base method.
func (m *MockIServiceRepository) Create(arg0 context.Context, arg1 *models.Service) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIServiceRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIServiceRepository)(nil).Create), arg0, arg1)
}

// DeleteOne mocks base method.
func (m *MockIServiceRepository) DeleteOne(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOne", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOne indicates an expected call of DeleteOne.
func (mr *MockIServiceRepositoryMockRecorder) DeleteOne(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOne", reflect.TypeOf((*MockIServiceRepository)(nil).DeleteOne), arg0, arg1, arg2)
}

// GetAll mocks base method.
func (m *MockIServiceRepository) GetAll(arg0 context.Context, arg1 string, arg2, arg3 int) ([]models.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]models.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockIServiceRepositoryMockRecorder) GetAll(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockIServiceRepository)(nil).GetAll), arg0, arg1, arg2, arg3)
}

// GetOne mocks base method.
func (m *MockIServiceRepository) GetOne(arg0 context.Context, arg1, arg2 string) (models.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOne", arg0, arg1, arg2)
	ret0, _ := ret[0].(models.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOne indicates an expected call of GetOne.
func (mr *MockIServiceRepositoryMockRecorder) GetOne(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOne", reflect.TypeOf((*MockIServiceRepository)(nil).GetOne), arg0, arg1, arg2)
}
