// Code generated by MockGen. DO NOT EDIT.
// Source: escort-book-escort-profile/repositories (interfaces: ITimeCategoryRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "escort-book-escort-profile/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockITimeCategoryRepository is a mock of ITimeCategoryRepository interface.
type MockITimeCategoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockITimeCategoryRepositoryMockRecorder
}

// MockITimeCategoryRepositoryMockRecorder is the mock recorder for MockITimeCategoryRepository.
type MockITimeCategoryRepositoryMockRecorder struct {
	mock *MockITimeCategoryRepository
}

// NewMockITimeCategoryRepository creates a new mock instance.
func NewMockITimeCategoryRepository(ctrl *gomock.Controller) *MockITimeCategoryRepository {
	mock := &MockITimeCategoryRepository{ctrl: ctrl}
	mock.recorder = &MockITimeCategoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITimeCategoryRepository) EXPECT() *MockITimeCategoryRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockITimeCategoryRepository) Count(arg0 context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockITimeCategoryRepositoryMockRecorder) Count(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockITimeCategoryRepository)(nil).Count), arg0)
}

// GetAll mocks base method.
func (m *MockITimeCategoryRepository) GetAll(arg0 context.Context, arg1, arg2 int) ([]models.TimeCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", arg0, arg1, arg2)
	ret0, _ := ret[0].([]models.TimeCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockITimeCategoryRepositoryMockRecorder) GetAll(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockITimeCategoryRepository)(nil).GetAll), arg0, arg1, arg2)
}

// GetById mocks base method.
func (m *MockITimeCategoryRepository) GetById(arg0 context.Context, arg1 string) (models.TimeCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", arg0, arg1)
	ret0, _ := ret[0].(models.TimeCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockITimeCategoryRepositoryMockRecorder) GetById(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockITimeCategoryRepository)(nil).GetById), arg0, arg1)
}
